name: Pylint

on: [push]

env:
  API_URL: ${{ secrets.API_URL }}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.6"

      - name: Test env vars for python
        run: python -c 'import os;print(os.environ)'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
      - name: Test with pytest
        run: |
          pytest

      - name: List directories
        run: |
          ls -la
      - name: Go up
        run: |
          cd ..
      - name: List workspace
        run: |
          ls ${{github.workspace}}

      - name: Run main program
        working-directory: ${{github.workspace}}
        run: |
          python scraper.py
